### ISSUE TITLE
Zadanie 1 TODO LIST

### ISSUE THREAD

**Issue by kjasamil** [kjasamil/SISE24kjnw#1]
# Zadanie 1 Część programistyczna

**Problemy ogólne, techniczne**
- [x] wczytywanie planszy z pliku
- [x] generowanie planszy wzorcowej (różne rozmiary)
- [x] wykonywanie i cofanie ruchów
- [x] sprawdzanie ruchów dozwolonych
- [x] szukanie pola pustego bądź dowolnej liczby w planszy
- [ ] optymalizacja? 

**Zaimplementowane metody rozwiązywania**
- [x] "w głąb" DFS
- [x] "wszerz" BFS
- [x] A* - metryka Hamminga
- [x] A* - metryka Manhattan
      
**Zawartość pliku z rozwiązaniem**
- [x] ilość wykonanych ruchów
- [x] ciąg liter oznaczających rozwiązanie
- [x] -1 gdy program nie znajdzie rozwiązania (i tylko -1)
      
**Zawartość pliku ze statystykami**
- [x] ilość wykonanych ruchów 
- [x] -1 gdy program nie znajdzie rozwiązania (i tylko -1)
- [x] ilość stanów odwiedzonych
- [x] ilość stanów przetworzonych
- [x] maksymalna osiągnięta głębokość rekursji
- [x] czas rozwiązywania

# Zadanie 1 Część badawcza
      
- [ ] PRZEBADANO WSZYSTKIE UKŁADY POCZĄTKOWE UKŁADANKI W ODLEGŁOŚCIACH 1-7 OD UKŁADU WZORCOWEGO (W SUMIE 413 UKŁADÓW)

**Algorytmy DFS i BFS**

Przebadano kolejność przeszukiwania sąsiedztwa:
- [ ] RDUL
- [ ] RDLU
- [ ] DRUL
- [ ] DRLU
- [ ] LUDR
- [ ] LURD
- [ ] ULDR
- [ ] ULRD

**Algorytm A***

Użyto heurystyk:
- [ ] miara Manhattan
- [ ] odległość Hamminga

**Wykresy**

Dla każdego kryterium należy wykonać wykresy:

- średnie arytmetyczne wyznaczone dla strategii BFS (dla wszystkich porządków przeszukiwania łącznie), DFS (dla wszystkich porządków przeszukiwania łącznie) oraz A* (dla obu heurystyk łącznie) względem głębokości rozwiązania
- średnie arytmetyczne wyznaczone dla strategii BFS względem głębokości rozwiązania z podziałem na poszczególne porządki przeszukiwania
- średnie arytmetyczne wyznaczone dla strategii DFS względem głębokości rozwiązania z podziałem na poszczególne porządki przeszukiwania
- średnie arytmetyczne wyznaczone dla strategii A* względem głębokości rozwiązania z podziałem na poszczególne heurystyki

- [ ] Kryterium I: Długość znalezionego rozwiązania
- [ ] Kryterium II: Liczba stanów odwiedzonych
- [ ] Kryterium III: Liczba stanów przetworzonych
- [ ] Kryterium IV: Maksymalna osiągnięta głębokość rekursji
- [ ] Kryterium V: Czas trwania procesu obliczeniowego
